### PR TITLE
Location of plugin on file system should not longer be supplied

### PR DESCRIPTION
**Pull request by jordanfilteau1995**
Signed-off-by: Jordan Filteau <jfilteau@rocketsoftware.com>

### CODE REVIEW

**Comment by jordanfilteau1995** [comment]
@1000TurquoisePogs  @fkovinAtRocket

**Comment by fkovinAtRocket** [comment]
```
      let contentPath = path.join(this.location, "web");
      if (!fs.existsSync(contentPath)) {
        [...]
      } else {
        [...]
        this.pluginPath = contentPath;
      }
```
So basically this is saying `plugin.pluginPath = plugin.location + "/web"` which I find confusing: why would a plugin have a plugin path that is different from its location?  The variable name is confusing.

What problem is this solving? You're talking about exportDef() --  does this have to deal with the /plugins root service?

**Comment by 1000TurquoisePogs** [comment]
Fyodor - you may want to take another brief look as I just went over this and suggested and had changes pushed.

**Comment by fkovinAtRocket** [comment]
Wow, it changed right as I was looking at it.

**Comment by fkovinAtRocket** [comment]
OK, looks pretty safe now.

**Pull request merged**
